<?php if (count($this->paginator)): ?>
    <table>
        <thead>
            <tr>
                <th>Hostname</th>
                <th>Public IP Address</th>
                <th>Backend IP Address</th>
                <th>Datacenter</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($this->paginator as $hardware): ?>
                <tr>
                    <td><?= $hardware->hostname; ?>.<?= $hardware->domain?></td>
                    <td><?= $hardware->primaryIpAddress; ?></td>
                    <td><?= $hardware->primaryBackendIpAddress; ?></td>
                    <td><?= $hardware->datacenter->longName ?></td>
                    <td>
                        <a href="<?= $this->url(array('controller' => 'hardware', 'action' => 'view', 'hardwareId' => $hardware->id));?>">View</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?= $this->paginationControl($this->paginator, 'Sliding', 'hardware/list.phtml'); ?>